name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1
  provider: ^5.0.0
  geolocator: ^7.0.1
  http: ^0.13.0
  dartssh: ^1.0.3+3
  speech_to_text: ^3.1.0
  flutter_tts: ^3.0.0
  smooth_star_rating: ^1.1.1
  autocomplete_textfield: any
  permission_handler: ^6.1.1

dependency_overrides:
  http: ^0.12.2
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/icons8-baguette-100.png
     - assets/images/icons8-bakery-100.png
     - assets/images/icons8-birthday-cake-100.png
     - assets/images/icons8-bread-100.png
     - assets/images/icons8-bread-and-rye-100.png
     - assets/images/icons8-cake-100.png
     - assets/images/icons8-croissant-100.png
     - assets/images/icons8-kawaii-bread-100.png
     - assets/images/icons8-kawaii-cupcake-100.png
     - assets/images/icons8-macaron-100.png
     - assets/images/icons8-pie-100.png
     - assets/images/icons8-search.gif
     - assets/images/Weichardt.jpg
     - assets/images/Beumer.jpg
     - assets/images/Christa.jpg
     - assets/Weich/icons8-bagel-100.png
     - assets/Weich/icons8-baguette-bread-100.png
     - assets/Weich/icons8-bread-100.png
     - assets/Weich/icons8-bread-loaf-100.png
     - assets/Weich/icons8-hamburger-100.png
     - assets/Weich/icons8-naan-100.png
     - assets/Weich/icons8-pretzel-100.png
     - assets/Weich/icons8-sandwich-100.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
